openapi: 3.0.1
info:
  description: "This is a a movie API for DesJardins Exercice"
  version: "1.0.0"
  title: "DesJardins Entrevue"
  contact:
    email: "amine.elkhlifi@gmail.com"
servers:
  - url: /api
paths:
  /movie/{id}:
    get:
      tags:
        - "movie"
      summary: "Find movie by ID"
      description: "Returns a single movie"
      operationId: "getMovieById"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of movie to return"
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1


      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieDto"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Movie not found"
  /movie:
    post:
      summary: Add a new Movie
      operationId: addMovie
      requestBody:
        description: Movie to be added in database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieDto'
        required: "true"
      responses:
        200:
          description: Movie Added
          content:
            application/json:
              schema:
                type: integer
                format: int64
      x-codegen-request-body-name: movie


components:
  schemas:
    MovieDto:
      type: "object"
      required:
        - "title"
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        actors:
          type: array
          items:
            $ref: "#/components/schemas/ActorDto"
    ActorDto:
      type: "object"
      required:
        - "firstName"
        - "lastName"
      properties:
        firstName:
          type: string
        lastName:
          type: string
        movies:
          type: array
          items:
            $ref: "#/components/schemas/MovieDto"